version: '3'

services:
  postgresql:
    image: postgres
    user: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  django_gunicorn:
    build:
      context: .
    volumes:
      - static:/static
    ports:
      - '8000:8000'
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - '80:80'
    depends_on:
      - django_gunicorn

volumes:
  static: