FROM python:latest

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV LANG C.UTF-8
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=10

WORKDIR /drf

COPY . .

RUN pip install -r /drf/requirements.txt

ENTRYPOINT ["sh", "entrypoint.sh"]