# Generated by Django 4.2.5 on 2023-09-24 06:06

from django.db import migrations
from django_celery_beat.models import IntervalSchedule, PeriodicTask, PeriodicTasks

def create_task(apps, schema_editor):
    """
    Notify users that course witch they subscribed is updated (email send).
    """
    interval = IntervalSchedule.objects.create(
        every=1,
        period=IntervalSchedule.HOURS
    )
    task = PeriodicTask.objects.create(
        interval=interval,
        name='course-update-notification',
        task='apps.academy.tasks.course_update_notification',
    )
    PeriodicTasks.update_changed()

class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('academy', '0005_alter_course_last_update_alter_lesson_created_and_more'),
    ]

    operations = [
        migrations.RunPython(create_task)
    ]
